name: SPDF Action Build
on:
 push:
   branches:
    - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Set Up Python 3.11
     uses: actions/setup-python@v3
     with:
       python-version: 3.11   
   - uses: actions/checkout@master
     with:
       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
   - name: Build and Commit
     uses: iSOLveIT/sphinx-pdf-generate-action@main
     with:
       config_file_path: './docs/conf.py'
       target_branch: 'gh-pages'
   - name: Push changes
     uses: ad-m/github-push-action@master
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       branch: gh-pages
